name: 'Lint'

on:
  push:
  pull_request:

jobs:
  terraform_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Format
      run: terraform fmt -check

  tofu_lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: OpenTofu - Setup Tofu
      uses: opentofu/setup-opentofu@v1.0.3

    - name: OpenTofu init
      run: tofu init -backend=false

    - name: OpenTofu Validate
      run: tofu validate

    - name: OpenTofu Format
      run: tofu fmt -check

